### ISSUE TITLE
NewMessageForm is broken in 1.11.7

### ISSUE THREAD

**Issue by volksman** [pinax/pinax-messages#38]
The empty queryset breaks things.

```python
to_user = UserModelChoiceField(queryset=get_user_model().objects.none)
```

should be 

```python
to_user = UserModelChoiceField(queryset=get_user_model().objects.none())
```

I have a PR (pr #37) setup to fix this AND remove dependancy on DUA

**Comment by grahamu** [comment]
Great catch @volksman!

FWIW, locally I added a test class:

```
class TestForms(BaseTest):

    def test_new_message_form(self):
        """Verify form instantiation without a hookset for `to_user` queryset"""
        NewMessageForm(user=self.brosner, initial={"to_user": self.brosner.pk})

    def test_new_message_form_multiple(self):
        """Verify form instantiation without a hookset for `to_user` queryset"""
        NewMessageFormMultiple(user=self.brosner, initial={"to_user": self.brosner.pk})
```

The tests don't really assert anything, but they do fail with an exception because the `none()` issue.

Since this fix has nothing to do with requiring login, I'd really like to see this fix in a separate PR. Separate PRs allows evaluation of each idea on its own merits.

I'll push my tests to master. Then, once you add a *form only* PR fix and everything passes I'll merge that PR to master with gratitude for your thoughtfulness. Thanks!

**Comment by volksman** [comment]
See PR #39

**Comment by volksman** [comment]
Above PR accepted and merged.  Closing issue.
