### ISSUE TITLE
Add this project to django packages?

### ISSUE THREAD

**Issue by gitanupam** [pinax/pinax-messages#49]
This project is missing in https://djangopackages.org/grids/g/messaging/. I think its worth adding it there

**Comment by gitanupam** [comment]
Sorry, it seems to be already there under a different name (https://djangopackages.org/packages/p/user_messages/)

**Comment by grahamu** [comment]
Reopening this @paltman because the underlying problem still exists. djangopackages does not have an entry for pinax-messages, and the existing entry is woefully out of date. Removing the one and adding the other would be good.

https://djangopackages.org/packages/p/user_messages/
https://djangopackages.org/grids/g/messaging/

**Comment by morenoh149** [comment]
fixed https://djangopackages.org/packages/p/pinax-messages/ in future for small things like this its best to just diy.

**Comment by KatherineMichel** [comment]
@morenoh149 Thanks for doing that. Didn't know DIY was an option there.
